name: Deploy to Firebase Hosting
on: {push: {branches: [main]}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: {node-version: '20'}

      - run: npm install -g firebase-tools

      # Write the secret to disk – the *only* place you reference the secret
      - name: Write service-account key
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > ${{ github.workspace }}/sa.json

      # (optional) prove the file is really there
      - name: Sanity-check key
        run: |
          echo "::group::listing"
          ls -l ${{ github.workspace }}/sa.json
          echo "::endgroup::"

      - name: Deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: firebase deploy --only hosting --project mythical-height-451619-v9
